// src/review/take-review.ts
// T10 — Zod port of skills/_shared/schemas/take-review.schema.json.
//
// A take review is the reviewer's structured observation of one generated take,
// judged against that clip's contract. It lives in src/review/ rather than
// src/narrative/ because it is produced by the reviewer and consumed by the
// retake protocol (T11); the narrative side only reads it back.
//
// The design point worth preserving: this schema separates *observation* from
// *judgement*. `observed_end_state`, `completed_beats` and `continuity_breaks`
// are what the reviewer saw; `verdict` is what it decided. Keeping them apart is
// what lets T11 change the retake policy without invalidating past reviews.

import { z } from 'zod';
import {
  ObservationConfidence,
  SourceStatus,
  StateBlob,
  TakeVerdict,
} from '../narrative/enums.js';

export const TakeReview = z
  .object({
    project_id: z.string(),
    clip_id: z.string(),
    take_id: z.string(),

    /** The clip status this take was reviewed from. */
    source_status: SourceStatus,

    verdict: TakeVerdict,

    observed_start_state: StateBlob,
    observed_end_state: StateBlob,

    /** Beats the contract asked for and the take delivered. */
    completed_beats: z.array(z.string()),
    /** Beats the contract asked for and the take did not deliver. */
    incomplete_beats: z.array(z.string()),
    /**
     * Beats that fired but were reserved for a later clip. These are the
     * expensive failure: the take may look fine in isolation while having
     * stranded the clip that was supposed to deliver the beat.
     */
    unexpected_completed_beats: z.array(z.string()),

    continuity_breaks: z.array(z.unknown()),
    accepted_deviations: z.array(z.unknown()),

    observation_confidence: ObservationConfidence,
    uncertainties: z.array(z.string()),

    /**
     * Set when the reviewer could not decide on its own. Honouring this is what
     * stops a low-confidence automated verdict from silently burning credit on
     * rerolls the user would not have authorised.
     */
    requires_user_confirmation: z.boolean(),
  })
  .strict();

export type TakeReviewT = z.infer<typeof TakeReview>;

/**
 * Consistency rules between the observation fields and the verdict.
 *
 * These are not stylistic. A review that reports incomplete beats while
 * returning `accept` will be treated by the retake protocol as a finished clip,
 * and the missing beat is never generated by anything.
 */
export function validateTakeReviewConsistency(review: TakeReviewT): string[] {
  const problems: string[] = [];

  const completed = new Set(review.completed_beats);
  for (const beat of review.incomplete_beats) {
    if (completed.has(beat)) {
      problems.push(`beat "${beat}" is reported both completed and incomplete`);
    }
  }
  for (const beat of review.unexpected_completed_beats) {
    if (completed.has(beat)) {
      problems.push(
        `beat "${beat}" is listed as both an expected and an unexpected completion`,
      );
    }
  }

  if (review.verdict === 'accept') {
    if (review.incomplete_beats.length > 0) {
      problems.push(
        `verdict "accept" contradicts ${review.incomplete_beats.length} incomplete beat(s); ` +
          `use "accept_with_deviation" or "repair"`,
      );
    }
    if (review.continuity_breaks.length > 0) {
      problems.push(
        `verdict "accept" contradicts ${review.continuity_breaks.length} continuity break(s); ` +
          `an accepted break belongs in accepted_deviations`,
      );
    }
  }

  if (review.verdict === 'accept_with_deviation' && review.accepted_deviations.length === 0) {
    problems.push(
      'verdict "accept_with_deviation" requires at least one entry in accepted_deviations, ' +
        'otherwise the deviation being accepted is not recorded anywhere',
    );
  }

  if (review.observation_confidence === 'low' && !review.requires_user_confirmation) {
    problems.push(
      'low observation_confidence must set requires_user_confirmation, otherwise an ' +
        'unreliable verdict can trigger a paid retake without the user being asked',
    );
  }

  return problems;
}

/** Parses and enforces the cross-field rules. Prefer over `TakeReview.parse`. */
export function parseTakeReview(input: unknown): TakeReviewT {
  const review = TakeReview.parse(input);
  const problems = validateTakeReviewConsistency(review);
  if (problems.length > 0) {
    throw new z.ZodError(
      problems.map((message) => ({
        code: z.ZodIssueCode.custom,
        path: ['verdict'],
        message,
      })),
    );
  }
  return review;
}
